name: AIPR 
description: Create an issue and have it solved by our pull request using Open AI.
branding:
  icon: 'code'
  color: 'blue'

jobs:
  chatgpt_code_generation:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'AIPR')
    steps:
      - name: Test env
        run: |
          echo ${{ vars }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate code with openai API
        id: openai
        env:
          OPEN_AI_API_KEY: ${{ env.OPEN_AI_API_KEY }}
        run: |
          python .github/scripts/aipr.py

      - name: Create topic branch and commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -b chatgpt
          git add .
          git commit -m "Generated code by ChatGPT || echo "No changes to commit"
          git push --set-upstream origin chatgpt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Code generated by ChatGPT "
          body: "This PR is generated by ChatGPT"
          labels: "ChatGPT,auto-generated"
          token: ${{ env.GITHUB_TOKEN }}