name: AIPR 
description: Create an issue and have it solved by our pull request using Open AI.
branding:
  icon: 'code'
  color: 'blue'
inputs:
  openai_api_key:
    description: 'Open AI API Key'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: 'repo'
    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: alexanmtz/AIPR
        token: ${{ github.token }} # Use the PAT stored as a secret
        path: 'scripts'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install aiohttp==3.8.2
        pip install openai===0.28.1

    - name: Generate code with openai API
      shell: bash
      id: openai
      env: 
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: |
        echo "Generating code with OpenAI API"
        echo "Getting the input from the repo which called the workflow: ${{ env.openai_api_key }}"
        echo "Open AI API KEY on the env: $OPENAI_API_KEY"
        python ./scripts/aipr.py
    - name: apply changes
      shell: bash
      run: |
        cd repo
        git config user.name "GitHub Actions Bot powered by AIPR"
        git config user.email "pull-request@aipr.com"
        git checkout -b AIPR-generated-${{ github.event.issue.number }}
        git add .
        git commit -m "Generated code by AIPR"
        git push --set-upstream origin AIPR-generated-${{ github.event.issue.number }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: 'repo'
        branch: AIPR-generated-${{ github.event.issue.number }}
        base: ${{ github.event.repository.default_branch }}
        title: "Code generated by AIPR"
        body: "This PR is generated by AIPR, it closes #${{ github.event.issue.number }}"
        labels: "AIPR-generated, auto-generated, bot"
        token: ${{ github.token }}